### ISSUE TITLE
Clicks are not detected outside of parents

### ISSUE THREAD

**Issue by Su386yt** [EssentialGG/Elementa#140]
**Describe the bug**
If you create an object that has a negative coordinate, or a coordinate outside the parent, the onMouseClick event will not trigger. onMouseEnter and onMouseLeave still trigger however.

**To Reproduce**
1. Create a parent object
2. Create a child of the parent object, with a location outside the parent object
3. Give the parent object an onMouseClick event

**Expected behavior**
The click event should trigger (as does the onMouseEnter and onMouseLeave)

**Comment by Sychic** [comment]
This seems to be intended as click events are not propagated when the click is not within the components bounds. On the other hand, mouse movement related events aren't properly checked for bounding and always propagate. This sounds more like an issue with the mouse movement events rather than the clicked event.

Is there a particular use case for this that cannot be circumvented by designing the component hierarchy differently?

**Comment by Su386yt** [comment]
> Is there a particular use case for this that cannot be circumvented by designing the component hierarchy differently?

![image](https://github.com/EssentialGG/Elementa/assets/83100266/50bbd9c7-be42-47ea-9eae-75f35f364c24)

I personally encountered it here, where each of the announcements is a child of the previous, with the ``x`` set at ``110.percent``. This allows for the next announcement to be at the end of the wrapped text, no matter the size of the text. I don't exactly see how this could be possible, without doing something like ``previousAnnouncement.getBottom().pixels``, but then the pixels don't automatically rescale

**Comment by Sychic** [comment]
> > Is there a particular use case for this that cannot be circumvented by designing the component hierarchy differently?
> 
> ![image](https://private-user-images.githubusercontent.com/83100266/342198313-50bbd9c7-be42-47ea-9eae-75f35f364c24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3OTczNTcsIm5iZiI6MTcxOTc5NzA1NywicGF0aCI6Ii84MzEwMDI2Ni8zNDIxOTgzMTMtNTBiYmQ5YzctYmU0Mi00N2VhLTllYWUtNzVmMzVmMzY0YzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAxMjQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNGE3YjJkYTgyYTU3OWZkMTFiYTA4YTU0OTk5NmI3ZGQyZThmZTFkZjA4NzY2N2EyYzQ2ZWE5ODJiYWJjNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hZvYygKeLJrymeP7HZt8HxtuaDp8KD_zOAFj6kJ__OY)
> 
> I personally encountered it here, where each of the announcements is a child of the previous, with the `x` set at `110.percent`. This allows for the next announcement to be at the end of the wrapped text, no matter the size of the text. I don't exactly see how this could be possible, without doing something like `previousAnnouncement.getBottom().pixels`, but then the pixels don't automatically rescale

You should be able to create a container and then position each announcement using SiblingConstraint for Y.

**Comment by Su386yt** [comment]
Although that wouldn't use percents tho. Could a possible change be letting sibling constraint have a percent parameter (if there isn't already)?

**Comment by Sychic** [comment]
Percents of what? You can always combine multiple constraints to achieve what you want.

**Comment by Su386yt** [comment]
Percent of width or percent of height. From my understanding, the pad is the same as say ``5.pixels``. Is there any way to get the pad to do ``5.percent``?

**Comment by Sychic** [comment]
5 percent of what

**Comment by Su386yt** [comment]
The parent component's width/height, same as if you were to do ``x = 5.percent``

**Comment by Sychic** [comment]
I don't see why you couldn't?

**Comment by Su386yt** [comment]
Oh right! Thank you!
